services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - 5006:5006
    environment:
      ACTUAL_LOGIN_METHOD: openid

    volumes:
      - /root/volumes/actual:/data
    healthcheck:
      # Enable health check for the instance
      test: ["CMD-SHELL", "node src/scripts/health-check.js"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    # restart: unless-stopped
