services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - /root/volumes/postgres-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_POSTGRES_PASSWORD}
